### ISSUE TITLE
Different results when running predict twice

### ISSUE THREAD

**Issue by hannorein** [dtamayo/spock#3]
When I run `model.predict(sim)` multiple times, I don't get the same answer.

**Comment by dtamayo** [comment]
Thanks, that's just because it's rerunning to the sim from the final state, so not doing anything. Easy fix, but depends on whether we end up caching the short integration outputs. Will leave this here so we don't forget!

**Comment by dtamayo** [comment]
New version now makes a sim.copy() by default. Also added a flag to disable the behavior if you know what you're doing since it does hurt performance by ~20%
